/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type QueryMsg = {
  query_is_selected: {
    node: Addr;
    round_id: string;
    [k: string]: unknown;
  };
} | {
  query_all_values: {
    [k: string]: unknown;
  };
} | {
  get_history_of_rounds: {
    [k: string]: unknown;
  };
};
export type Addr = string;