const coinGeckoIdToChainNameMap = {
  "avalanche-2": "avalanche",
  ethereum: "ethereum",
  moonbeam: "moonbeam",
  polkadot: "polkadot",
  "matic-network": "polygon",
  agoric: "agoric",
  "aioz-network": "aioz",
  "akash-network": "akash",
  "markhor-meta": "arkh",
  assetmantle: "assetmantle",
  axelar: "axelar",
  "band-protocol": "bandchain",
  bitsong: "bitsong",
  chihuahua: "chihuahua",
  cosmos: "cosmoshub",
  "crescent-network": "crescent",
  "crypto-com-chain": "cronos",
  desmos: "desmos",
  evmos: "evmos",
  graviton: "gravitybridge",
  "injective-protocol": "injective",
  "iris-network": "irisnet",
  "juno-network": "juno",
  kava: "kava",
  kujira: "kujira",
  "lum-network": "lumnetwork",
  osmosis: "osmosis",
  persistence: "persistence",
  regen: "regen",
  secret: "secretnetwork",
  sifchain: "sifchain",
  stargaze: "stargaze",
  stride: "stride",
  tgrade: "tgrade",
  umee: "umee",
};

export const coinGeckoIds = Object.keys(coinGeckoIdToChainNameMap);

export const chainNames = Object.values(coinGeckoIdToChainNameMap);
